name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
     
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Install OpenCV
      run: |
        mkdir -p app/libs
        wget https://github.com/piruin/opencv-android/releases/download/3.4.1/opencv-android.aar -O app/libs/opencv.aar
        ls -la app/libs/opencv.aar
        file app/libs/opencv.aar  
    - name: Build
      run: ./gradlew assembleDebug
      

