name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
     
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Download OpenCV AAR
      run: |
        mkdir -p app/libs
        curl -L https://github.com/opencv/opencv/releases/download/4.8.0/opencv-4.8.0-android-sdk.zip -o opencv.zip
        unzip opencv.zip
        cp opencv-4.8.0-android-sdk/sdk/native/libs/* app/libs/
    
    - name: Build
      run: ./gradlew assembleDebug
      

