      name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle
     
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Download OpenCV AAR
      run: |
        mkdir -p app/src/main/jniLibs
        mkdir -p app/libs
        cp -r OpenCV-android-sdk/sdk/native/libs/* app/src/main/jniLibs/
        cp OpenCV-android-sdk/sdk/java/opencv.aar app/libs/  
        find app/src/main/jniLibs -name '*.so' | xargs ls -la
        ls -la app/libs/
    
    - name: Build
      run: ./gradlew assembleDebug
      

